# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/base.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tristate_0_0/design_1_tristate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tristate_0_0 || ORIG_REF_NAME==design_1_tristate_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tristate_0_1/design_1_tristate_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tristate_0_1 || ORIG_REF_NAME==design_1_tristate_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb_to_grayscale_wra_0_0/design_1_rgb_to_grayscale_wra_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rgb_to_grayscale_wra_0_0 || ORIG_REF_NAME==design_1_rgb_to_grayscale_wra_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fast_brief_0_0/design_1_fast_brief_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fast_brief_0_0 || ORIG_REF_NAME==design_1_fast_brief_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_feature_matcher_0_0/design_1_feature_matcher_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_feature_matcher_0_0 || ORIG_REF_NAME==design_1_feature_matcher_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_imp_auto_pc_0/design_1_axi_mem_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_imp_auto_pc_0 || ORIG_REF_NAME==design_1_axi_mem_imp_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_0/design_1_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_0/design_1_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_0 || ORIG_REF_NAME==design_1_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dvi2rgb_1_0/design_1_dvi2rgb_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dvi2rgb_1_0 || ORIG_REF_NAME==design_1_dvi2rgb_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_1_0/design_1_rgb2dvi_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_1_0 || ORIG_REF_NAME==design_1_rgb2dvi_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xpm_cdc_gen_0_0/design_1_xpm_cdc_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xpm_cdc_gen_0_0 || ORIG_REF_NAME==design_1_xpm_cdc_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_interface_0_0/design_1_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_interface_0_0 || ORIG_REF_NAME==design_1_interface_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xpm_cdc_gen_0_1/design_1_xpm_cdc_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xpm_cdc_gen_0_1 || ORIG_REF_NAME==design_1_xpm_cdc_gen_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xpm_cdc_gen_1_0/design_1_xpm_cdc_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xpm_cdc_gen_1_0 || ORIG_REF_NAME==design_1_xpm_cdc_gen_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xpm_cdc_gen_1_1/design_1_xpm_cdc_gen_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xpm_cdc_gen_1_1 || ORIG_REF_NAME==design_1_xpm_cdc_gen_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xpm_cdc_gen_3_0/design_1_xpm_cdc_gen_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xpm_cdc_gen_3_0 || ORIG_REF_NAME==design_1_xpm_cdc_gen_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1_1/design_1_axi_smc_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1_1 || ORIG_REF_NAME==design_1_axi_smc_1_1} -quiet] -quiet

# XDC: /home/jstrz/slam/corner_detection.gen/sources_1/bd/design_1/design_1_ooc.xdc
